on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install -g yarn
      - run: yarn --frozen-lockfile
      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          prettier: true
