on:
  push:
    branches:
      - '*'

jobs:
  test:
    if: ${{ github.repository_owner == 'UniSA-PS-Web-Pain' }}
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          build: npm run build
          start: npm run start
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
